#!/bin/sh

export BROWSER=~/bin/browser.sh
export EDITOR=~/bin/editor.sh
export PATH="${HOME}/bin:${PATH}"

eval $(gpg-agent --daemon)
eval $(ssh-agent)

# Apps
pulseaudio --daemonize
dunst &
alacritty --class weechat -e ~/bin/weechat.sh &
keepassxc &
unclutter &
xautolock -time 10 -locker slock &
syncthing &
~/bin/mail.sh &
quiterss &
(sleep 2 && xsetroot) &
dino &
slack --startup &
viber &

# Keyboard setup
xset r rate 180 30
xset dpms 600 600 600
setxkbmap -option "grp:lswitch" "us,hr"
xrdb ~/.Xdefaults
xmodmap ~/.xmodmap
xset dpms 600 600 600
xset +dpms

exec i3
