#!/bin/sh

export BROWSER=~/bin/browser.sh
export EDITOR=lvim
export PATH="${HOME}/bin:${PATH}"

eval $(gpg-agent --daemon)
eval $(ssh-agent)

# Apps
pulseaudio --daemonize
dunst &
hexchat &
keepassxc &
unclutter &
xautolock -time 10 -locker slock &
syncthing &
quiterss &
(sleep 2 && xsetroot) &
dino &
slack --startup &
viber &
~/bin/mail.sh &
offlineimap &
birdtray &

# Keyboard setup
xrdb ~/.Xdefaults
xmodmap ~/.xmodmap

exec i3
